### ISSUE TITLE
WARP API returns incorrect results

### ISSUE THREAD

**Issue by sguermond** [mannkind/seattlewaste2mqtt#17]
Hi there! 

@millercentral found that the API used here returns incorrect data, and @gabosom found an API that returns the correct data for Seattle Utilities. You can find more details [in this issue](https://github.com/mampfes/hacs_waste_collection_schedule/issues/50), and API implementation [in this PR](https://github.com/mampfes/hacs_waste_collection_schedule/pull/51).

**Comment by mannkind** [comment]
Oh! Well isn't that interesting. 
Thanks for the report @sguermond.

Looks like the new API is a bit more complicated, but maybe not too difficult to fix. 🤔 I'll look deeper into the issue/PR over the next few days.
